SCHEME STDERR
#SCHEME SAMPLESIZE

#ADDFILTER MAF > 0.01
AVERAGEFREQ ON
MINMAXFREQ ON
#GENOMICCONTROL ON

MARKER MARKER_ID
ALLELE EFFECT_ALLELE OTHER_ALLELE
EFFECT BETA
STDERR SEBETA
PVALUE PVALUE
#WEIGHT NS
FREQLABEL EAF
PROCESS SNPs-study1.txt.gz
PROCESS SNPs-study2.txt.gz
PROCESS SNPs-study3.txt.gz

OUTFILE METAANALYSIS_ .tbl
ANALYZE HETEROGENEITY
QUIT
